# Generated by Django 4.1.2 on 2022-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='Sets and Reps',
        ),
    ]
